[package]
name = "ini-persist-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
regex = "1"
syn = "2"
